<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
<head>
    <title>JPublish: empty ST application [$page.Path$]</title>
    <link rel="stylesheet" href="$request.ContextPath$/styles/simple.css" type="text/css">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
</head>

<body>
	$content$
	<p>2007, <a href="http://weblog.flop.ca">FloP.ca</a></p>
</body>
</html>
