#!/bin/sh

clear
JETTY_HOME="/usr/local/java/servers/jetty"
OPTIONS=" -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n"
JAVA_OPTIONS="$OPTIONS -Djetty.home=$JETTY_HOME "
java $JAVA_OPTIONS -DSTART=$JETTY_HOME/extra/etc/start-plus.config -jar $JETTY_HOME/start.jar jprss.xml $1 $2 $3 $4
