package org.jpublish.module.cayenne.demo.auto;

/** Class _TodoType was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _TodoType extends org.apache.cayenne.CayenneDataObject {

    public static final String IS_DEFAULT_PROPERTY = "isDefault";
    public static final String NAME_PROPERTY = "name";

    public static final String ID_PK_COLUMN = "id";

    public void setIsDefault(Boolean isDefault) {
        writeProperty("isDefault", isDefault);
    }
    public Boolean getIsDefault() {
        return (Boolean)readProperty("isDefault");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
}
