package org.jpublish.module.cayenne.demo.auto;

/** Class _Todo was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Todo extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String EXPIRES_AT_PROPERTY = "expiresAt";
    public static final String IS_DONE_PROPERTY = "isDone";
    public static final String TYPE_PROPERTY = "type";
    public static final String USER_PROPERTY = "user";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedAt(java.util.Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public java.util.Date getCreatedAt() {
        return (java.util.Date)readProperty("createdAt");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setExpiresAt(java.util.Date expiresAt) {
        writeProperty("expiresAt", expiresAt);
    }
    public java.util.Date getExpiresAt() {
        return (java.util.Date)readProperty("expiresAt");
    }
    
    
    public void setIsDone(Boolean isDone) {
        writeProperty("isDone", isDone);
    }
    public Boolean getIsDone() {
        return (Boolean)readProperty("isDone");
    }
    
    
    public void setType(org.jpublish.module.cayenne.demo.TodoType type) {
        setToOneTarget("type", type, true);
    }

    public org.jpublish.module.cayenne.demo.TodoType getType() {
        return (org.jpublish.module.cayenne.demo.TodoType)readProperty("type");
    } 
    
    
    public void setUser(org.jpublish.module.cayenne.demo.User user) {
        setToOneTarget("user", user, true);
    }

    public org.jpublish.module.cayenne.demo.User getUser() {
        return (org.jpublish.module.cayenne.demo.User)readProperty("user");
    } 
    
    
}
