package org.jpublish.module.cayenne.demo.auto;

import java.util.List;

/** Class _User was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _User extends org.apache.cayenne.CayenneDataObject {

    public static final String EMAIL_PROPERTY = "email";
    public static final String NAME_PROPERTY = "name";
    public static final String TODOS_PROPERTY = "todos";

    public static final String ID_PK_COLUMN = "id";

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void addToTodos(org.jpublish.module.cayenne.demo.Todo obj) {
        addToManyTarget("todos", obj, true);
    }
    public void removeFromTodos(org.jpublish.module.cayenne.demo.Todo obj) {
        removeToManyTarget("todos", obj, true);
    }
    public List getTodos() {
        return (List)readProperty("todos");
    }
    
    
}
